### ISSUE TITLE
Dataset preparation 

### ISSUE THREAD

**Issue by Suvi-dha** [sacmehta/YNet#1]
I am trying to train your code on my dataset and although I understand from the readme files how my RGB image file and annotation file should be named , But still I couldn't comprehend what these file name means
0
/valrgb/1339_1_1000_9800_1.33.png, /valannot/1339_1_1000_9800_1.33.png, 
0/valrgb/1529_1_6000_3000_1.33.png, /valannot/1529_1_6000_3000_1.33.png, 
0/valrgb/2204_1_18400_11800_1.33.png, /valannot/2204_1_18400_11800_1.33.png

It is not clear from the readme files that what does "1.33"here means. Also, why there is a "0" before valrgb directory. 

Also, I am sure you haven't written those lines in text files for train and validation one by one, for each image. You must have used some tool that generates this kind of text files. It would be helpful to conform my dataset accordingly if you could share that tool's information. 

Thanks!

**Comment by sacmehta** [comment]
1.33 is nothing but the scale at which WSI was resized. This is just the nomenclature that I followed for saving the images and could vary.

Y-Net makes use of classification and segmentation labels. So, each row in these text files is a tuple of 3 elements:

rgb image file name, corresponding segmentation label, corresponding classification label

0’s are the classification labels and it is after valrgb directory if you see it in a good text editor, say vim. Classification label is used in stage 2. If you are only interested in stage 1, then set this classification label as 0 (dummy value) or modify data loading scripts.

I didn’t use any tool to generate these files. Just a small python script. I don’t have it handy right now, but will upload it sometime later.

**Comment by Suvi-dha** [comment]
Ok, Got it. Thank you.
