### ISSUE TITLE
"instance-level probability map" generation code

### ISSUE THREAD

**Issue by monjoybme** [sacmehta/YNet#3]
I'm working on your YNet architecture. Could you please share the code for **instance-level probability map** generation? In the recent repository, only  **instance-level segmentation mask** generation code is available but no instance-level probability map code. 
Thanks in advance.

**Comment by sacmehta** [comment]
If you look at stage2, the models generate two outputs, one for segmentation and other for classification. From the output of classification branch, you can compute probability by first applying softmax and then pick the maximum probability value. To have instance probability map, you can create a tensor with the same size as input and then fill it with the probability that you computed earlier.

Hope this helps!

**Comment by monjoybme** [comment]
Thanks!

**Comment by cool-breeze-and-rain** [comment]
@monjoybme ,
hey, did you remember how to get the instance probability map?  I don't know how to fill it to a tensor

**Comment by monjoybme** [comment]
Please check the answer discussed above.

**Comment by cool-breeze-and-rain** [comment]
Yes, I have checked. But I don't know how to fill the tensor with the probability while the output size of classification branch just [1, 5]
