### ISSUE TITLE
I can't find the dataset in "https://www.bcsc-research.org/" website. Can you tell me the details of the download link? Thank you.

### ISSUE THREAD

**Issue by chuxiang93** [sacmehta/YNet#4]

**Comment by sacmehta** [comment]
Which dataset? The dataset we used in our research is not publicly available.

**Comment by chuxiang93** [comment]
> Which dataset? The dataset we used in our research is not publicly available.

I saw in the paper that you said the data was the same as the reference [2,10].
![image](https://user-images.githubusercontent.com/11666931/56005790-d49fb700-5d04-11e9-930e-859a984740ac.png)

Then I looked at the reference [10], "Learning to Segment Breast Biopsy Whole Slide Images". The paper says the data comes from reference “Breast Cancer Surveillance Consortium. http://www. bcsc-research.org/”. But I can't find the download link for the pathology images.
![image](https://user-images.githubusercontent.com/11666931/56005884-5099ff00-5d05-11e9-8648-29e53bbf3757.png)

I want to ask, has this code never been run on public datasets?
Thank you for your reply.

**Comment by sacmehta** [comment]
Public dataset: A version of this code is tested on volumetric images, which were publicly available as a part of BRATS competition. See our repository 3D-ESPNet for the same.

Regarding dataset: The images were collected from Breast cancer consortium. However, this does not provide annotated images. For annotations, our co-author, Dr. Joann Elmore, did a pathological study which is published in JAMA, a reputed medical journal. See references in our paper for details about the paper.
