### ISSUE TITLE
code not match paper

### ISSUE THREAD

**Issue by ray-lee-94** [sacmehta/YNet#5]
Thank you for your code sharing. 
I concern about that your code dose not match the setting your paper. Diagnostic classification result is worse if using segmentation mask. But your code uses none of the segmentation mask, the background and discriminative mask. No code to  caculate the frequency and Co-occurrence feature. I can't find any information about how to get the 44 dim feature vector. So i have my suspicions about your performance in the diagnostic classification task.

**Comment by sacmehta** [comment]
The code is only for Y-Net part (segmentation and saliency mask generation) and not for classification. 

Computing frequency and co-occurence features is trivial and can be easily done using either Python or Matlab. That is why we didn’t include that code.

BTW, on which dataset are you testing?

**Comment by sacmehta** [comment]
Read below document for more details about classification part:

https://digital.lib.washington.edu/researchworks/bitstream/handle/1773/40012/Mercan_washington_0250E_17308.pdf?sequence=1&isAllowed=y

**Comment by ray-lee-94** [comment]
Thank you for your quickly reply! I will read the dissertation.
