### ISSUE TITLE
source code of instance level probability map

### ISSUE THREAD

**Issue by shuuchen** [sacmehta/YNet#6]
Hi,

Thanks for disclosing the source code.

Could you please tell me where is the source code of instance level probability map ?
I cannot understand how to get the map from a predicted vector.

in main.py of stage2, I see the predicted vector is output1 at line 93.
Then a histogram is computed with size of 4*4 .

Is the histogram to be  instance level probability map ?

**Comment by sacmehta** [comment]
See #3
