### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by anonymously123456** [sacmehta/YNet#7]
I am trying to train your code on my dataset , but still I couldn't comprehend what these file name means.
for example ,  1222_1_1200_4800_4.jpg,     What does 1222 mean?   What does 1 mean? What does 1200 mean? and What does 4800 mean?
Thanks a lot!  Looking forward to your reply

**Comment by sacmehta** [comment]
This naming is specific to our dataset.

1222_1 means the first ROI in sample id 1222

1200_4800 means the crop_start_x and crop_end_x

4 means WSI scale (4x, 2x, 10x, etc.)

But you don't have to follow that.. You can use <img_name>, <class_id>

**Comment by anonymously123456** [comment]
Thanks for your reply, in stage2,  i use my way to name the trainrgb(1.png , 2.png, 3.png ....) , trainannot(1.png, 2.png, 3.png,. ...), valrgb(1.png, 2.png, 3.png,. ...) and valannot (1.png, 2.png, 3.png,. ...),   train.txt and val.txt is also  modified accordingly,  but the  foowing error occurs:
 
![image](https://user-images.githubusercontent.com/56376393/98634653-a8c03980-235e-11eb-9b9a-57d7179db0a3.png)
![image](https://user-images.githubusercontent.com/56376393/98634731-c2618100-235e-11eb-8752-1ff0d767acee.png)
![image](https://user-images.githubusercontent.com/56376393/98634770-d1483380-235e-11eb-9c96-b710892ee250.png)

**Comment by sacmehta** [comment]
Seems like file is not in the specified path.. Check for the file path and make sure its correct.
